// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvRhj6bgMoOhWQKZX0S_JegglOJ-dimgI',
    appId: '1:899106264237:android:0be9435bc79a0d319aa224',
    messagingSenderId: '899106264237',
    projectId: 'evently-app-6797a',
    storageBucket: 'evently-app-6797a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0mzU8UXd_Dwq-J9dz6Y5hp4f_qsOcrPk',
    appId: '1:899106264237:ios:3aa078afcbf799de9aa224',
    messagingSenderId: '899106264237',
    projectId: 'evently-app-6797a',
    storageBucket: 'evently-app-6797a.firebasestorage.app',
    iosBundleId: 'com.example.eventlyAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtTbY1iJjM6ccFPP-1FAdCPdz_Coatg-k',
    appId: '1:899106264237:web:3fca4eb8f9048ea79aa224',
    messagingSenderId: '899106264237',
    projectId: 'evently-app-6797a',
    authDomain: 'evently-app-6797a.firebaseapp.com',
    storageBucket: 'evently-app-6797a.firebasestorage.app',
    measurementId: 'G-J0MVFGKHGR',
  );
}
